dist: trusty
sudo: false
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
script:
- mvn clean package
after_script: mvn -q scm-publish:publish-scm
env:
  global:
  - secure: U8EbROkfASvjuWB92FmgDlE3OBXEQVKsHhjIQVqXfUN5K0NVTGLyJVs3Pg9Ux90rFFkH40I4WiV6olkp4MrqzLGSTdP2hJXxs0REuDuz5saFGgF+Jxj/RJqsjXvDeGQgAL+Oh8Qw8UnJqSaVSKXH0Q/soLtlYCKtXMwZkxnbk9Y=
