= Curriculum Vitae - Rafael M. Pestano
Rafael Pestano <rmpestano@gmail.com>
v2.0, July 30, 2016
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:experimental:
:source-language: asciidoc
:includedir: _includes

// Refs
:link-resume: http://rmpestano.github.io/resume
:link-twitter: https://twitter.com/realpestano


:link-ufrgs: http://www.ufrgs.br/
:link-procergs: http://www.procergs.rs.gov.br/
:link-jfrs: http://www.jfrs.jus.br/
:link-adv: http://www.advancedit.com.br/
:link-ecore: http://e-core.com/br/

:link-home: https://goo.gl/maps/NpRTv
:link-rsjug: http://www.rsjug.org/




//projects
:link-github: https://github.com/rmpestano
:ling-cukedoctor: http://github.com/rmpestano/cukedoctor
:ling-dbunit-rules: http://github.com/rmpestano/dbunit-rules
:link-conventions: http://conventions.github.io/home

//writting
:link-blog: http://rpestano.wordpress.com
:link-thesis: http://www.lume.ufrgs.br/handle/10183/110332

//other links
:link-jenkins: https://jenkins.io/
:link-artifactory: https://www.jfrog.com/open-source/
:link-sonar: http://www.sonarqube.org/

ifeval::["{backend}" == "html5"]
icon:file-pdf-o[] Read this resume {link-resume}/resume.pdf[in PDF here, role="external", window="_blank"]. +
endif::[]

ifeval::["{backend}" == "pdf"]
icon:html5[] Read this resume {link-resume}/resume.html[in HTML5 here, role="external", window="_blank"]. +
endif::[]

[discrete]
== Software Engineer / Developer

****

I'm a *Software Engineer/Developer* who works on *Java EE* platform and related technologies. +

I like to focus my work on coding/testing, deal with infrastructure (devops), prospecting new technologies, evangelizing and sharing knowledge with teammates and community.

Rafael has a bachelor degree of {link-resume}/#_education[Computer Science] and is a Software Developer/Engineer since *2007*. +
He is actually a software engineer at {link-procergs}[PROCERGS^]. +

He is passionate about IT and +Open Source+ so he contributes to {link-resume}#_open_source[Open Source projects] in many ways. +

Rafael attends and speaks at {link-resume}/#_conferences_presentations[conferences] on *Java EE*, like The Developers Conference and also {link-resume}/#_community[engage with community]. +

He blogs about Java EE and related technologies on his {link-blog}[personal blog^].

He's mainly working with Java enterprise web related technologies for about 7 years, has experience with agile methodologies and strong background on testing.

****

== Main interests

* Java EE
* Open source
* Agile methodologies
* Testing (junit/Arquillian/BDD)
* Continuous Delivery
* SOA / Microservices
* Docker and containers related technologies
* Documentation (Asciidoctor)
* Functional languages (Kotlin)

== Personal details

_Name_: Rafael Mauricio Pestano +
_WebSite / Social Media_: {link-blog}[blog] / icon:github[link={link-github}, role="external", window="_blank", alt="@rmpestano"] / icon:twitter[link={link-twitter}, role="external", window="_blank", alt="@realpestano"] +
_Location_: {link-home}["Porto Alegre, RS, Brazil", role="external", window="_blank"] +


== Professional Experience

=== Java EE Engineer / Developer at Procergs

icon:calendar[title="Period"] _August 2011 to Now (On going)_ +
icon:group[title="Employee"] {link-procergs}[PROCERGS - Data processing company of the State of Rio Grande do Sul, role="external", window="_blank"] +

--
[horizontal]
Position:: *Software Engineer - Java EE - Agile - DevOps* +
--

* Create and maintain in house JavaEE 6+ based solutions for speed up development
* Part of a Technical team which supports 300+ developers
* Prospecting new technologies (R&D)
* Evangelizing good practice and disciplines of agile methodologies such as testing and continuous delivery
* Migration of legacy technology to service based architecture
* Helps maintain infrastructure tools like {link-jenkins}[Jenkins]^, {link-sonar}[Sonar^] and {link-artifactory}[Artifactory^]
* worked 3 years (2011-2014) in internal software factory using scrum

==== Used technologies

* JavaEE 6/7 stack:
* Primefaces / Richfaces
* Arquillian / Cucumber / Selenium / Junit (tests)
* Asciidoctor (Documentation)
* Swagger (REST API)
* JBoss EAP 6/7 (application server)
* SVN
* OracleDB/Postgres
* Redmine/TFS


=== Java Developer at AdvancedIt

icon:calendar[title="Period"] _November 2010 to August 2011_ +
icon:group[title="Employee"] {link-adv}[AdvancedIt - Intelligence in information technology, role="external", window="_blank"] +

--
[horizontal]
Position:: *Java Developer* +
--

==== Used technologies

* Spring 3.x
* Hibernate 3.x
* JSF 1.1
* Richfaces
* Maven
* OC4J and tomcat application servers
* Nexus
* MyEclipse IDE
* Jasper reports
* OracleDB

=== Java Developer at e-Core

icon:calendar[title="Period"] _April 2010 to November 2010_ +
icon:group[title="Employee"] {link-ecore}[e-Core - Atlassian platinum partner, role="external", window="_blank"] +

--
[horizontal]
Position:: *Java Developer* +
--
* Worked customizing Atlassian Jira issue tracker for various clients
* Developed a JavaEE 5 JBoss Seam based web application

==== Used technologies

* JavaEE 5
* Hibernate 3.x
* JSF 1.2
* EJB 3
* Richfaces
* Jboss Seam
* Ant
* Jboss 5 application server
* Eclipse IDE
* mercurial
* Jasper reports
* MySql

=== Java trainee at JFRS

icon:calendar[title="Period"] _October 2008 to April 2010_ +
icon:group[title="Trainee"] {link-jfrs}[JFRS - Justiça Federal, role="external", window="_blank"] +

--
[horizontal]
Position:: *Java Trainee* +
--

Research and Development of Java EE 5 and Google Web Toolkit applications.


==== Used technologies

* JavaEE 5 stack
* JPA (toplink)
* JSF 1.2
* EJB 3
* Richfaces
* Glassfish 3 application server
* Netbeans IDE
* svn
* Jasper reports
* MySql
* JaxWS (apache axis)


== Technical Skills

Languages and Specifications:: Java SE, *Java EE* (JSF, BV, JPA, EJB, CDI, Servlet, JSP), J2EE, JavaScript, XML, CSS, AsciiDoc

Application Servers:: *JBoss EAP 6/7*, *WildFly 8*, Glassfish, Bea Weblogic and Apache Tomcat

Frameworks and Libraries:: http://arquillian.org[*Arquillian*^], http://forge.jboss.org/[JBoss Forge^], https://deltaspike.apache.org/[*Apache DeltaSpike*^], http://primefaces.org[Primefaces^], http://gatling.io/[Gatling^]

OS:: Linux (Ubuntu/Fedora) and Windows

Databases:: Oracle, Postgress, MySQL and HSQLDB

Software Engineering:: OOP, SOA/MS, DevOps, Design Patterns, Unit Testing, Integration Testing, BDD, Continuous Delivery

Tools:: Eclipse, *IntelliJ*, Netbeans, Maven, JIRA, Redmine, Subversion, *Git*, *Asciidoctor*, JMeter/Gatling, Jenkins, Sonar, Artifactory

Cloud:: Openshift, travisci, codeship

== Open Source

Contribute to projects::
I contribute in a different ways (code, documentation, blog, forums, conference,experimenting and opening issues) to severals projects like Asciidoctor, Arquillian, JBoss Forge and Deltaspike.

Some of my open source activities can be found here:

* {link-github}[Github account^]: General activity
* {link-cukedoctor}[Cukedoctor^]: BDD living documentation tool
* {link-dbunit-rules}[DBUnit Rules^]: Database testing tool for JUnit
* {link-conventions}[Conventions framework^]: Academical homegrown framework based on JavaEE 6 (NOT maintained anymore).



== Technical Writing

=== Publications

==== Graduation Thesis


* {link-thesis}[Towards a Software Metric for OSGi, role="external", window="_blank"] - Quality analysis in modular applications.


=== Blog

I frequently write blog posts at http://rpestano.wordpress.com/[rpestano.wordpress.com, role="external", window="_blank"].

== Conferences & Presentations

* TDC 2015, Porto Alegre, September 2015
** Coordinated Java tracking
** Presented http://rmpestano.github.io/talks/slides/forge-tdc-2015/[Fast Java EE develpment with JBoss Forge]
* TDC 2014, Porto Alegre, October 2014
** Presented http://pt.slideshare.net/rmpestano/presentation-40379978[Enterprise testing using Arquillian, role="external", window="_blank"]
* Braziljs, Porto Alegre, August 2012

My presentations slides can be found here: http://rmpestano.github.io/talks/

== Community

I am one of the coordinators of {link-rsjug}[Java user group of Rio Grade do Sul] (one of the first Brazilian JUGs).

== Languages Skills

* Portuguese : native language
* English : fluent (reading, writting); advanced (speaking)

== Education

=== Federal University of Rio Grande do Sul, Porto Alegre, Brazil

{link-ufrgs}[UFRGS, role="external", window="_blank"] +

icon:calendar[title="Period"] _2005-2014_ - *Bachelor Degree* +

== Interests

* Sport : Football (soccer) and weight/strength Training
* TV Shows: The walking dead, Prison break
* New technologies, Open Source
* Family
* Beer
* Music
