= Curriculum Vitae - Rafael M. Pestano
Rafael Pestano <rmpestano@gmail.com>
Kismet Chameleon <kismet@asciidoctor.org>
:revnumber: {version} 
:revdate: Nov 2019
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:experimental:
:source-language: asciidoc
:includedir: _includes

// Refs
:link-resume: http://rmpestano.github.io/resume
:link-twitter: https://twitter.com/realpestano


:link-ufrgs: http://www.ufrgs.br/
:link-mobi: https://www.mobiquity.com/about-us
:link-procergs: http://www.procergs.rs.gov.br/
:link-jfrs: http://www.jfrs.jus.br/
:link-adv: http://www.advancedit.com.br/
:link-ecore: http://e-core.com/br/

:link-poa: https://goo.gl/maps/NpRTv
:link-ams: https://goo.gl/maps/CSs2qjtjradQpKbe6
:link-rsjug: http://www.rsjug.org/
:link-rsjug-site: https://rsjug.github.io/site/




//projects
:link-github: https://github.com/rmpestano
:link-cukedoctor: http://github.com/rmpestano/cukedoctor
:link-database-rider: https://database-rider.github.io/database-rider/
:link-adminfaces: http://github.com/adminfaces/
:link-last-changes: https://wiki.jenkins.io/display/JENKINS/Last+Changes+Plugin
:link-conventions: http://conventions.github.io/home

//writting
:link-blog: http://rpestano.wordpress.com
:link-thesis: http://www.lume.ufrgs.br/handle/10183/110332

//other links
:link-jenkins: https://jenkins.io/
:link-artifactory: https://www.jfrog.com/open-source/
:link-sonar: http://www.sonarqube.org/
:link-jekyll: https://jekyllrb.com/
:link-app-dynamics: https://www.appdynamics.com/
:link-wso2: https://wso2.com/

ifeval::["{backend}" == "html5"]
icon:file-pdf-o[] Read this resume {link-resume}/index.pdf[in PDF here, role="external", window="_blank"]. +
endif::[]

ifeval::["{backend}" == "pdf"]
icon:html5[] Read this resume {link-resume}/index.html[in HTML5 here, role="external", window="_blank"]. +
endif::[]

[discrete]
== Software Engineer / Developer

****

I'm a *Software Engineer/Developer* who works on *Java enterprise* applications using technologies such as `JakartaEE`, `MicroProfile` and `Spring/SpringBoot`. +

I like to focus my work on coding/testing, deal with infrastructure (devops), prospecting new technologies, evangelizing and sharing knowledge with teammates and community.

I have a bachelor degree of {link-resume}/#_education[Computer Science] and I am a Software Developer since *2007*. +

I'm actually working as a software engineer at {link-mobi}[Mobiquity^]. +

I am very passionate about IT and +Open Source+ and I contribute to {link-resume}#_open_source[Open Source projects] in many ways. +

I attend and speak at {link-resume}/#_conferences_presentations[conferences] on *Java Enterprise and JVM*, like The Developers Conference and I also {link-resume}/#_community[engage with community]. +

I blog about Java Enterprise and related technologies on my {link-blog}[personal blog^].

I'm mainly working with Java enterprise web related technologies for 10+ years, I have experience with agile methodologies and strong background on testing.

****

== Main interests

* Jakarta EE/ MicroProfile
* Spring
* SpringBoot
* Open source
* Agile methodologies
* Testing (junit/Arquillian/BDD)
* Continuous Delivery
* SOA / Microservices
* Docker and containers related technologies
* Documentation (Asciidoctor)
* Functional languages (Kotlin/Groovy)
* Cloud (AWS and OpenShift)

== Personal details

`Name:` Rafael Mauricio Pestano +
`WebSite / Social Media:` {link-blog}[blog] / icon:github[link={link-github}, role="external", window="_blank", alt="@rmpestano"] / icon:twitter[link={link-twitter}, role="external", window="_blank", alt="@realpestano"] +
`Location:` {link-ams}["Amsterdam, Netherlands", role="external", window="_blank"] +

== Professional Experience

=== Backend Engineer at Mobiquity Inc

icon:calendar[title="Period"] _November 2019 to Now (on going)_ +
icon:group[title="Employeer"] {link-mobi}[Mobiquity Inc - Global digital consultancy, role="external", window="_blank"] +
icon:map-marker[title="Location"] {link-ams}["Amsterdam, Netherlands", role="external", window="_blank"] +
--
[horizontal]
Position:: *Senior Backend Engineer - Spring/SpringBoot - Agile - DevOps* +

* Develop rest APIs consumed by multiple banks and health insurance providers in the Netherlands
* Write BDD tests (in Kotlin) for verifying functionality (DoD)
* Use agile methodologies/ceremonies such as Scrum
* Work in a cloud based infrastructure provided by AWS
--


==== Used technologies

* Java 11
* Spring 5 and SpringBoot 2
* ADLM: Jira/Jenkins/GitHub
* Sonar
* Elastic Search
* Cucumber
* Kotlin
* AWS: S3/SQS/DynamoDB

=== Java EE Engineer / Developer at PROCERGS

icon:calendar[title="Period"] _August 2011 to October 2019_ +
icon:group[title="Employeer"] {link-procergs}[PROCERGS - Data processing company of the State of Rio Grande do Sul, role="external", window="_blank"] +
icon:map-marker[title="Location"] {link-poa}["Porto Alegre, RS, Brazil", role="external", window="_blank"] +

--
[horizontal]
Position:: *Software Engineer - Java EE - Agile - DevOps* +
--

* Create and maintain in house JavaEE based solutions for speed up internal development
* Part of a Technical team which supports 200+ developers
* Prospecting new technologies (R&D)
* Evangelizing good practice and disciplines of agile methodologies such as testing and continuous delivery
* Migration of legacy technology to service based architecture
* Helps maintain infrastructure tools like {link-wso2}[WSO2^], {link-app-dynamics}[AppDynamics^], {link-jenkins}[Jenkins^], {link-sonar}[Sonar^] and {link-artifactory}[Artifactory^]
* Develop and maintain an internal (devops) tool to help developers in _App Servers management_ (deploy applications, view logs, start/stop apps, logging configuration, create system props, enable blue/green deployment etc...)
* Write documentation and blog about best practices
* Drive/help teams to build delivery pipelines on Jenkins
* Migration of legacy applications (JavaEE 5 or below) to new stack (Java EE 7/8)
* worked 3 years (2011-2014) in internal software factory using scrum

==== Used technologies

* JavaEE 6/7 stack (mainly EJB, CDI, JaxRS/RestEasy/Jersey, JSF, JPA/Hibernate)
* Primefaces / Richfaces
* Arquillian / Cucumber / Selenium / Junit (tests)
* Asciidoctor (Documentation)
* Swagger (REST API)
* JBoss EAP 6/7 (application server)
* SVN/GIT
* OracleDB/Postgres
* Redmine/TFS
* MAT (Memory analyser Tool)
* Jenkins
* Sonar
* WSO2
* AppDynamics
* Artifactory

TIP: Currently internalizing an internal cloud solution based on Kubernetes (PKS).


=== Java Developer at AdvancedIt

icon:calendar[title="Period"] _November 2010 to August 2011_ +
icon:group[title="Employeer"] {link-adv}[AdvancedIt - Intelligence in information technology, role="external", window="_blank"] +
icon:map-marker[title="Location"] {link-poa}["Porto Alegre, RS, Brazil", role="external", window="_blank"] +

--
[horizontal]
Position:: *Java Developer* +
--

==== Used technologies

* Spring 3.x
* Hibernate 3.x
* JSF 1.1
* Richfaces
* Maven
* OC4J and tomcat application servers
* Nexus
* MyEclipse IDE
* Jasper reports
* OracleDB

=== Java Developer at e-Core

icon:calendar[title="Period"] _April 2010 to November 2010_ +
icon:group[title="Employeer"] {link-ecore}[e-Core - Atlassian platinum partner, role="external", window="_blank"] +
icon:map-marker[title="Location"] {link-poa}["Porto Alegre, RS, Brazil", role="external", window="_blank"] +

--
[horizontal]
Position:: *Java Developer* +
--
* Worked customizing Atlassian Jira issue tracker for various clients
* Developed a JavaEE 5 JBoss Seam based web application
* Mercurial VCS

==== Used technologies

* JavaEE 5
* Hibernate 3.x
* JSF 1.2
* EJB 3
* Richfaces
* Jboss Seam
* Ant
* Jboss 5 application server
* Eclipse IDE
* mercurial
* Jasper reports
* MySql

=== Java trainee at JFRS

icon:calendar[title="Period"] _October 2008 to April 2010_ +
icon:group[title="Trainee"] {link-jfrs}[JFRS - Justiça Federal, role="external", window="_blank"] +
icon:map-marker[title="Location"] {link-poa}["Porto Alegre, RS, Brazil", role="external", window="_blank"] +
--
[horizontal]
Position:: *Java Trainee* +
--

Research and Development of Java EE 5 and Google Web Toolkit applications.


==== Used technologies

* JavaEE 5 stack
* JPA (toplink)
* JSF 1.2
* EJB 3
* Richfaces
* Glassfish 3 application server
* Netbeans IDE
* svn
* Jasper reports
* MySql
* JaxWS (apache axis)
* GWT (with ExtJS)


== Technical Skills

Languages and Specifications:: Java SE 7/8, Kotlin, Groovy, JavaScript, JSON, YAML, CSS/Less/Sass, AsciiDoc, Swagger

Application Servers:: *JBoss EAP 6/7*, *WildFly 8/10*, Glassfish/Payara, Bea Weblogic and Apache Tomcat/Tomee

Frameworks and Libraries:: *Java EE* (JSF, BV, JPA, EJB, CDI, JAX-RS, Servlet, JSP), J2EE, http://arquillian.org[*Arquillian*^], http://forge.jboss.org/[JBoss Forge^], https://deltaspike.apache.org/[*Apache DeltaSpike*^], http://primefaces.org[Primefaces^], http://gatling.io/[Gatling^].

OS:: Linux (*Ubuntu*/Fedora), MacOS and Windows

Databases:: Oracle, Postgress, MySQL and HSQLDB/H2

Software Engineering:: OOP, SOA/MS, DevOps, Design Patterns, Unit Testing, Integration Testing, BDD, *Continuous Delivery*

Tools:: Eclipse, IntelliJ, Netbeans, Maven, JIRA, Redmine, Subversion, Git, Asciidoctor, JMeter/Gatling, Jenkins, Sonar, Artifactory, WSO2 and AppDynamics

Cloud:: PKS, Openshift, travisci

ADLM:: TFS


== Open Source

Contribute to projects::
I contribute in different ways (code, documentation, blog, forums, conference,experimenting and opening issues) to severals projects like Asciidoctor, Arquillian, JBoss Forge and Deltaspike. 

My general OSS activity can be found on {link-github}[Github here^].

Following is notable projects I've created and maintain:
  
* {link-cukedoctor}[Cukedoctor^]: BDD living documentation tool
* {link-database-rider}[Database Rider (formerly named DBUnit Rules)^]: Database testing tool for JUnit
* {link-adminfaces}[AdminFaces^]: A premium responsive JSF template and Primefaces theme based on Bootstrap and AdminLTE
* {link-last-changes}[LastChanges^]: A plugin which generates rich HTML diffs for *Jenkins* builds
* {link-rsjug-site}[RSJug^]: {link-jekyll}[Jekyll^] based site for our local Jug
* {link-conventions}[Conventions framework^]: Academical homegrown framework based on JavaEE 6 (NOT maintained anymore).


== Technical Writing

=== Publications

==== Graduation Thesis


* {link-thesis}[Towards a Software Metric for OSGi, role="external", window="_blank"] - Quality analysis in modular applications.


=== Blog

I frequently write blog posts at http://rpestano.wordpress.com/[rpestano.wordpress.com, role="external", window="_blank"].

== Conference presentations

* TDC 2018, Porto Alegre, December 2018
** Presented http://rmpestano.github.io/talks/slides/tdc-dbunit/index.html#/[Testing your persistence layer with Database Rider]
* TDC 2017, Porto Alegre, November 2017
** Presented http://rmpestano.github.io/talks/slides/javaee-pipeline/index-en.html[JavaEE Pipeline as code with Docker, Jenkins and Sonar]
* TDC 2016, Porto Alegre, October 2016
** Coordinated Java tracking
* TDC 2015, Porto Alegre, September 2015
** Presented http://rmpestano.github.io/talks/slides/forge-tdc-2015/[Fast Java EE development with JBoss Forge]
** Coordinated Java tracking
* TDC 2014, Porto Alegre, October 2014
** Presented http://pt.slideshare.net/rmpestano/presentation-40379978[Enterprise testing using Arquillian, role="external", window="_blank"]
 
My presentations slides can be found here: http://rmpestano.github.io/talks/

== Community

I was one of the coordinators of {link-rsjug}[Java user group of Rio Grade do Sul] (The first Brazilian JUG), from 2015 to 2019.

== Languages Skills

* Portuguese : native language
* English : fluent (reading, writting); advanced (speaking)

== Education

=== Federal University of Rio Grande do Sul, Porto Alegre, Brazil

{link-ufrgs}[UFRGS, role="external", window="_blank"] +

icon:calendar[title="Period"] _2005-2014_ - *Bachelor Degree* +

== Personal Interests

* Sport : Football (soccer), weight/strength Training and running
* TV Shows: The walking dead, Prison break, Stranger Things etc...
* New technologies, Open Source
* Family (Father of two beautiful little girls)
* Beer
* Music
* Charcuterie (home made sausages lover)